services:
  - type: web
    name: deepchest
    env: python
    plan: free
    buildCommand: pip install --prefer-binary --no-cache-dir -r requirement.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: SECRET_KEY
        value: change-me-in-production
