services:
  - type: web
    name: deepchest
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: SECRET_KEY
        value: change-me-in-production
